# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    checkLatest: true
- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g @ionic/cli'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g cordova'  
- task: CmdLine@2
  inputs:
    script: 'ionic cordova platform add android'

- task: CmdLine@2
  inputs:
    script: 'ionic cordova build android --prod --release'
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/outputs/apk/release/app*.apk'
    apksignerKeystoreFile: 'my-release-key.jks'
    apksignerKeystorePassword: 'aaron12345'